### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Snarkly** [download13/ipfstube#1]
You need to start a ipfstube twitter account to help promote it and to get feedback.

**Comment by download13** [comment]
Right now I just kind of threw it out for others interested in IPFS. Later it might be a backing service for another project, but until then I'm trying to keep it low key (the VPS it's on only has 20GB of disk space).

**Comment by Snarkly** [comment]
Is this project still active, I hope so it's a great idea.

**Comment by JigmeDatse** [comment]
I was just informed of LBRY which seems to have some serious issues in my mind.  Based on what I can tell about it right now it looks like the claims around "democratizing the video on the web" are anything but true (though I may be misunderstanding certain things about it) whereas I can't see anything with this which suggests it does anything "anti-democratic".

**Comment by download13** [comment]
I started a twitter account for it and added a logo. I'm guessing it won't gain a whole lot of traction without a bettery directory/library service for content though.

**Comment by JigmeDatse** [comment]
I think that a directory/library service may be more of a separate project entirely.  I'm not really sure.  It is good to be able to host, and play the videos in a distributed manner.  It would be great if we could even figure out *how* to index content on IPFS in the first place.

**Comment by download13** [comment]
Yeah, keeping it separate is probably for the best. If nobody else creates a content directory I was going to slap together an elasticsearch-backed web interface where people could post stuff.
