### ISSUE TITLE
Mine added video can not be played via different IP

### ISSUE THREAD

**Issue by slrslr** [download13/ipfstube#11]
Hello, i can not find any instructions on how [the site](https://ipfstube.erindachtler.me) works.
So i clicked to select a video file. It plays after i clicked play button couple of times.
But when i [open the resulting URL via proxy, then video does not play](https://usproxy.vpnbook.com/browse.php?u=IilExMXzkMwzmoSe8KoFxt8X448zWn1CCNsvkM1bMxlnWrm0Q8OdhbYC6zch32zVSZIIplEj4c8fHLYP1cElRg%2FjPOAz4u%2FWOkzt84k%3D&b=0&f=norefer).

Firefox developer console (F12 key) shows:

> Trying url http://127.0.0.1:8080/ipfs/browse.php
> browse.php:63:4
> HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://usproxy.vpnbook.com/browse.php?u=IilExMXzkMwzmoSe8KoFxt8X448zWn1CCNsvkM1bMyF6aP3PO%2BumgIBE5Ag63XHnJoAUpQ%3D%3D&b=0 failed.
> browse.php
> Cannot play media. No decoders for requested formats: text/html

**Comment by download13** [comment]
Can you post the direct urls you are talking about? The proxy urls seem to have timed out.

**Comment by slrslr** [comment]
Hi, [here is the example link](https://ipfstube.erindachtler.me/v/QmYUHr4Q2iHXttBpQzFYBLfWtZq12AEC9CLhvbHiYj2Uyi) i paste into the [proxy site](https://www.vpnbook.com/webproxy) and after clicking to play the video, errors i mentioned above appear.

**Comment by slrslr** [comment]
I think this is not the problem of the ipfstube, other proxy works to play the video: https://www.croxyproxy.com/
