### ISSUE TITLE
Videos have been deleted!

### ISSUE THREAD

**Issue by Pacius** [download13/ipfstube#14]
Is there possible to use my own ipfs node to save the videos,the network is NOT data-persistent,i have lost a lot of videos.

Please tell us how to run this on our own ipfs node,rather than some random node of the ipfs network.

thanks

**Comment by download13** [comment]
Yeah, I should probably put a notice about that on the front page...

The instance I'm running is on a VPS with only 20GB of storage, so old stuff gets overwritten/unpinned as new stuff is uploaded. It's really meant as a temporary seeder.

If you head over to the [ipfs install instructions](https://docs.ipfs.io/introduction/install/) you can set up your own node on your computer or a server if you've got one. Then just use `ipfs add {filename}` if you've got a file, or `ipfs pin {hash}` if it's already on the network and you want to make sure you keep a copy.
