### ISSUE TITLE
not playing video

### ISSUE THREAD

**Issue by Snarkly** [download13/ipfstube#2]
I uploaded a music video that was a flv and it was 8.6 mb It seemed to upload to ipfstube with no problem but it will not play back the video. Here's the hash QmV8bnFzVzCAL4Yf3c9PVjue7WtNWrH5pZDCU5nQRUKmaK
And when I put the hash in the search bar and click on watch I get unable to load video, took you a screenshot. ![ipfstube](https://cloud.githubusercontent.com/assets/8492776/14934504/117c6b86-0e80-11e6-9ae6-fc0d2c8e7c80.png)

**Comment by download13** [comment]
I don't think the video tag in most browsers can play FLV formatted videos. The player is basically just a video tag with some JS to help it pick an endpoint.

As for the uploading: don't tell anyone, but it just adds the file right to the local IPFS daemon. I was going to do some kind of checking to make sure it was at least a video file, but it was easier to just proxy connections from nginx straight through. If someone removed the `accept` attribute from the file input they could upload any file at all, not just videos.

**Comment by Snarkly** [comment]
Ok I gotcha.

**Comment by download13** [comment]
Thanks!
