### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Snarkly** [download13/ipfstube#4]
If possible try to set up ipfstube to look more like this program called MediaDrop. http://mediadrop.net/ MediaDrop has more of a youtube look and feel to it. You might even be able to set up MediaDrop itself on IPFS, I'm not for sure though I'm not a coder.

**Comment by download13** [comment]
IPFSTube is just meant to be a video player. I was going to make a separate site as a directory service later, but haven't gotten around to it yet.
